# Generated by Django 2.1.8 on 2019-12-03 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('info', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('concern', models.CharField(blank=True, max_length=50, null=True)),
                ('outcount', models.CharField(blank=True, max_length=50, null=True)),
                ('char', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'books',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Booktype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'booktype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Borrowbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowdate', models.DateTimeField(blank=True, db_column='borrowDate', null=True)),
                ('restoredata', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('bookid', models.ForeignKey(blank=True, db_column='bookid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='duanxin.Books')),
            ],
            options={
                'db_table': 'borrowbook',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('dutydate', models.DateTimeField(blank=True, null=True)),
                ('leavedate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'manager',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('credit', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'reader',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Readergrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('maxmaney', models.IntegerField(blank=True, null=True)),
                ('dateamount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'readergrade',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'role',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='reader',
            name='grandid',
            field=models.ForeignKey(blank=True, db_column='grandid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='duanxin.Readergrade'),
        ),
        migrations.AddField(
            model_name='reader',
            name='roleid',
            field=models.ForeignKey(blank=True, db_column='roleid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='duanxin.Role'),
        ),
        migrations.AddField(
            model_name='manager',
            name='roleid',
            field=models.ForeignKey(blank=True, db_column='roleid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='duanxin.Role'),
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='managerid',
            field=models.ForeignKey(blank=True, db_column='managerid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='duanxin.Manager'),
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='readerid',
            field=models.ForeignKey(blank=True, db_column='readerid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='duanxin.Reader'),
        ),
        migrations.AddField(
            model_name='books',
            name='typeid',
            field=models.ForeignKey(blank=True, db_column='typeid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='duanxin.Booktype'),
        ),
    ]
